### ISSUE TITLE
frp dashboard not works

### ISSUE THREAD

**Issue by terryzwt** [wenerme/charts#3]
Install command:
` helm install frps -n dsf-system wener/frps -f values.yaml`

values.yaml: 

```
configInline: |
  [common]
  dashboard_addr = 0.0.0.0
  dashboard_port = 7500
  dashboard_user = admin
  dashboard_pwd = admin

  bind_addr = 0.0.0.0
  bind_port = 80

  kcp_bind_port = 80
  vhost_http_port = 80
  vhost_https_port = 43

  bind_udp_port = 7001

  enable_prometheus = true
ports:
  http:
    port: 80
    servicePort: 80
    protocol: TCP
    ingresses:
    - name: "frps"
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: frp.local
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: frps
              port:
                name: dashboard
      tls:
      - secretName: tls-name
        hosts:
          - frp.local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: frp.local
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: frps
              port:
                name: dashboard
      tls:
      - secretName: tls-wild-dsf-davyin-net
        hosts:
          - frp.local
  https:
    port: 443
  udp:
    port: 7001
    protocol: UDP
  kcp:
    port: 80
    protocol: UDP
  dashboard:
    port: 7500

service:
  type: ClusterIP
```
after install , when I visit frp.local, it shows the error:
```
The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by [frp](https://github.com/fatedier/frp).

Faithfully yours, frp.
```
